### PR TITLE
feat: add env var functionality

### PR DESCRIPTION
**Pull request by iamacook**
This adds `@nestjs/config` and, as such, environmental variables.

Note: the `ConfigModule` is currently injected directly but a custom configuration module similar to [that from the gateway](https://github.com/5afe/safe-client-gateway-nest/tree/main/src/config) will be implemented in a subsequent PR.

### CODE REVIEW

**Review by schmanu — DISMISSED** [review]
💯 nice.

**Review by fmrsabino — COMMENTED** [review]
Why is `safe-gelato-relay-service` now a submodule?

**Comment by iamacook** [comment]
> Why is `safe-gelato-relay-service` now a submodule?

It was just for organisation sake that I moved it. Should it not be?

**Comment by fmrsabino** [comment]
> > Why is `safe-gelato-relay-service` now a submodule?
> 
> It was just for organisation sake that I moved it. Should it not be?

This Pull Request is about adding the `@nestjs/config`. I think folder structure is out of scope for this change.

If we consider changing the structure of the project:
- Why is it a submodule?
- Why this structure and not any other structure?

Currently the starting point is: https://github.com/5afe/safe-client-gateway-nest – if there's a good reason to change the structure (eg.: standard approach, advantages of submodules, etc.) then I think we should also do that for the Safe Client Gateway.

**Comment by iamacook** [comment]
> This Pull Request is about adding the `@nestjs/config`. I think folder structure is out of scope for this change.

I have reverted the submodule so that this PR just adds `@nestjs/config`.

**Comment by schmanu** [comment]
> Currently the starting point is: https://github.com/5afe/safe-client-gateway-nest – if there's a good reason to change the structure (eg.: standard approach, advantages of submodules, etc.) then I think we should also do that for the Safe Client Gateway.

But wasn't it like the structure in the Safe Client Gateway? One module for each route + the AppModule importing them all?

I agree with keeping PRs small and scoped, I just don't understand how the approach previously was different from the Safe Client Gateway.

**Review by schmanu — DISMISSED** [review]

**Comment by fmrsabino** [comment]
> > Currently the starting point is: https://github.com/5afe/safe-client-gateway-nest – if there's a good reason to change the structure (eg.: standard approach, advantages of submodules, etc.) then I think we should also do that for the Safe Client Gateway.
> 
> But wasn't it like the structure in the Safe Client Gateway? One module for each route + the AppModule importing them all?
> 
> I agree with keeping PRs small and scoped, I just don't understand how the approach previously was different from the Safe Client Gateway.

Yeah this was a misunderstanding. I was referring to the following change:
image

Unfortunately I cannot comment directly on that change 😅 

Regarding the `relay` "module" I completely agree with the change!

**Review by fmrsabino — APPROVED** [review]
🚀 🚀

**Comment by iamacook** [comment]
> Yeah this was a misunderstanding. I was referring to the following change: image

Thanks for the clarification. This was an easy oversight. I'm not sure how that came to be but I've removed it now.

**Pull request merged**
